### ISSUE TITLE
Support for Tahiti cards please

### ISSUE THREAD

**Issue by webheadx1** [zjazz/zjazz_amd_miner#3]
Support for Tahiti cards please , it finds gpu hd7950 but unsupported many thanks.

**Comment by zjazz** [comment]
I tried to support Tahiti cards about a week about. When testing the miner with them I saw that it didn't work properly and I found a technical restriction. Supporting Tahiti cards needs to rewrite and maintain a specific version of all the 22 algorithms contained in X22i (it only happens with Tahiti family). This is a huge amount of work and unfortunately I can't spend so much time just to support 1 specific family of cards, so I decided that Tahiti cards will not be supported, I'm sorry :(
