### ISSUE TITLE
stratum error all the time

### ISSUE THREAD

**Issue by Sharpeich** [zjazz/zjazz_amd_miner#5]
zjazz AMD miner v1.1

13:07:26 | ko | Pool #0 | URL: "stratum+tcp://eu1.fairmine.pro:7200" | User: "SYh56Smy42HamYhTLuLUDWTvsdP1cELD5P" | Password: "c=SUQA"
13:07:26 | ko | GPUs | #0 gfx900
13:07:26 | ko | API available at 127.0.0.1:4011
13:07:26 | ko | Algorithm x22i
13:07:26 | ko | Connecting to: stratum+tcp://eu1.fairmine.pro:7200
13:07:26 | ko | Connected to: stratum+tcp://eu1.fairmine.pro:7200
13:07:36 | ko | ERROR: Subscribe to stratum+tcp://eu1.fairmine.pro:7200 failed
13:07:36 | ko | Will retry in 30 seconds

after 30 seconds same error

**Comment by zjazz** [comment]
I talked with you on discord, it was a connection issue on your side

**Comment by Sharpeich** [comment]
i tried from different locations from different computers (win7 x64 and
win10 x64) - all the same stratum error. never experienced stratum issues
on other coins (algoes) and miners. (

сб, 20 окт. 2018 г. в 13:39, zjazz <notifications@github.com>:
